- app/assets/javascripts/components/page.cjsx
- app/assets/javascripts/components/questions/decimal_numeric_question.cjsx
- app/assets/javascripts/components/questions/numeric_question.cjsx
- config/questionnaire.json
> Added numeric question

- app/assets/javascripts/components/page.cjsx
- app/assets/javascripts/components/questionnaire.cjsx
- app/assets/javascripts/components/questions/agency_question.cjsx
- app/assets/javascripts/components/questions/date_question.cjsx
- app/assets/javascripts/components/questions/decimal_numeric_question.cjsx
- app/assets/javascripts/components/questions/file_question.cjsx
- app/assets/javascripts/components/questions/form.cjsx
- app/assets/javascripts/components/questions/gps_question.cjsx
- app/assets/javascripts/components/questions/multi_answer_question.cjsx
- app/assets/javascripts/components/questions/numeric_question.cjsx
- app/assets/javascripts/components/questions/single_answer_question.cjsx
- app/assets/javascripts/components/questions/text_question.cjsx
- app/assets/javascripts/stores/questionnaire_store.cjsx
- app/assets/stylesheets/application.css
- app/assets/stylesheets/components/page-controls.scss
- app/assets/stylesheets/components/page.scss
- config/questionnaire.json
- vendor/assets/stylesheets/skeleton.css
We've got quite some changes here, so I thought it's best to split this into two parts.
In this episode:
* Add GpsQuestion (with geolocation API)
* add Skeleton.css
* new `pages` structure in `questionnaire.json`. `pages` is now an array of objects, allowing us to add `title` and future needed properties in the `page` object.
> Complete questionnaire (part 1)

- README.md
- app/assets/javascripts/components/questionnaire.cjsx
- app/assets/javascripts/components/save_button.cjsx
- app/assets/javascripts/components/submit_button.cjsx
- app/assets/javascripts/stores/questionnaire_store.cjsx
- app/controllers/reports_controller.rb
- config/questionnaire.json
Introduces features for save, submit and autosave 🙉:
- Save button is always present and saves, then updates the report at any time
- Submit button will only appear when required questions (set with `"required": true`) have been answered
- Report will save on every page forward/back
- Report will autosave every 60 seconds
- Submit button will mark the questionnaire as `"state": "submitted"`, do a final update to the database and then return the user to the index page listing all questionnaires
> Submit button

- .travis.yml
- Gemfile
- Gemfile.lock
- test/test_helper.rb
This is to add test coverage reporting to Code Climate (and also generate coverage files locally)
> Test coverage

- Gemfile
- Gemfile.lock
- app/controllers/reports_controller.rb
- app/jobs/csv_export_job.rb
- app/mailers/notification_mailer.rb
- app/views/notification_mailer/notify_user_of_csv_export_ready.html.erb
- app/views/notification_mailer/notify_user_of_csv_export_ready.text.erb
- app/views/reports/index.html.erb
- config/environments/development.rb
- config/routes.rb
- lib/modules/csv_builder.rb
- test/jobs/csv_export_job_test.rb
CSV Export for most columns, will revisit to complete once the looping sections have been finalised for the live/dead/parts apes in the db
> Csv export

- app/helpers/report_helper.rb
- app/models/report.rb
- test/models/report_test.rb
> Add apes to reports table

- app/assets/stylesheets/components/table.scss
- app/views/admin/users/index.html.erb
- app/views/agencies/index.html.erb
- app/views/reports/_table.html.erb
> Responsive table mixin

- app/assets/stylesheets/components/table.scss
- app/models/report.rb
- app/views/admin/users/index.html.erb
- app/views/agencies/_form.html.erb
- app/views/agencies/index.html.erb
- app/views/agencies/show.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_links.html.erb
- app/views/layouts/_header.html.erb
- app/views/notification_mailer/notify_user_of_account_creation.text.erb
- app/views/reports/_table.html.erb
- app/views/reports/summary.html.erb
- app/views/reports/validate.html.erb
- lib/modules/csv_builder.rb
Card for reference: https://trello.com/c/6dDbENHe/95-minor-fixes
> Minor fixes

- app/controllers/registrations_controller.rb
- app/views/devise/registrations/edit.html.erb
Card for reference: https://trello.com/c/uHud6YRB/89-edit-my-profile-fixes
> My Profile fixes

- app/controllers/reports_controller.rb
- app/views/layouts/application.html.erb
- config/locales/en.yml
Card for reference: https://trello.com/c/nsVXk5oF/87-update-csv-export-success-text
> Csv export message

- app/controllers/agencies_controller.rb
- app/views/layouts/application.html.erb
- config/locales/en.yml
Card for reference: https://trello.com/c/bL07wYQN/92-add-warning-message-when-deleting-agencies-with-associated-users
> add warning when deleting agencies with users

- app/assets/javascripts/components/questions/date_question.cjsx
- app/assets/stylesheets/application.css
- app/models/report.rb
- package.json
- vendor/assets/stylesheets/react-datepicker.css
> Add react-datepicker and moment

- app/assets/stylesheets/components/navigation.scss
- app/assets/stylesheets/utilities/typography.scss
> Added responsive sub nav buttons and reduced h1 a little

- app/assets/javascripts/app.cjsx
- app/assets/javascripts/stores/questionnaire_store.cjsx
- app/assets/stylesheets/app.scss
- app/assets/stylesheets/components/alert.scss
- app/assets/stylesheets/components/questionnaire.scss
- app/assets/stylesheets/variables/colors.scss
- app/helpers/application_helper.rb
- app/views/layouts/_flash_notification.html.erb
- app/views/layouts/_navigation.html.erb
- app/views/layouts/application.html.erb
> Flash messages

- app/assets/javascripts/stores/questionnaire_store.cjsx
- app/controllers/reports_controller.rb
- app/controllers/validations_controller.rb
- app/views/reports/thank_you.html.erb
- app/views/validations/thank_you.html.erb
- config/routes.rb
- test/controllers/validations_controller_test.rb
> Thank you pages

- app/models/ability.rb
- app/views/reports/thank_you.html.erb
- app/views/validations/thank_you.html.erb
> Fixes for thank you pages

- app/assets/javascripts/stores/questionnaire_store.cjsx
- app/controllers/reports_controller.rb
- app/helpers/report_helper.rb
- app/views/reports/search.html.erb
- config/questionnaire/pages/incident.json.erb
- config/questionnaire/pages/incident/countries.json.erb
- db/migrate/20160831165044_add_genera_data_to_reports.rb
- db/schema.rb
- lib/modules/search_builder.rb
- test/controllers/reports_controller_test.rb
> Search update

- app/assets/stylesheets/utilities/u-classes.scss
- app/controllers/reports_controller.rb
- app/views/reports/_ape_summary.html.erb
- app/views/reports/summary.html.erb
Adds ape details without images
> Ape details

- .env.example
- Gemfile
- Gemfile.lock
- app/views/layouts/_header.html.erb
- config/initializers/sidekiq.rb
- config/routes.rb
- lib/modules/params_utils.rb
- Fixes page parameter showing in the search
- Adds sidekiq dashboard to figure out wtf is going on
> Styling fixes

- app/assets/stylesheets/utilities/u-classes.scss
- app/controllers/reports_controller.rb
- app/views/reports/_ape_summary.html.erb
> Added images to ape details

- app/assets/javascripts/app.cjsx
- app/assets/javascripts/modules/user_form_handler.cjsx
- app/assets/stylesheets/utilities/typography.scss
- app/controllers/reports_controller.rb
- app/models/role.rb
- app/views/admin/users/_form.html.erb
- app/views/admin/users/form/_change_password.html.erb
- app/views/admin/users/form/_contact.html.erb
- app/views/admin/users/form/_expertise.html.erb
- app/views/admin/users/form/_general.html.erb
- lib/modules/country_utilities.rb
Card for reference: https://trello.com/c/Xd702q68/118-new-user-page-fixes
> User creation form fixes

- app/assets/javascripts/components/question.cjsx
- app/assets/javascripts/components/questionnaire.cjsx
- app/assets/javascripts/stores/navigation_store.cjsx
- app/assets/javascripts/stores/questionnaire_store.cjsx
- app/controllers/reports_controller.rb
Card for reference: https://trello.com/c/NMS6Sv2G/117-view-of-full-report
> Full report view

- app/assets/javascripts/components/question.cjsx
- app/assets/javascripts/components/questions/single_answer_question.cjsx
- app/assets/javascripts/stores/questionnaire_store.cjsx
Card for reference: https://trello.com/c/y9D4CKrd/116-bug-other-please-specify-fields-not-being-saved
> Fix other field

- app/controllers/admin/users_controller.rb
- app/controllers/agencies_controller.rb
- app/controllers/reports_controller.rb
- app/views/admin/users/index.html.erb
- app/views/agencies/index.html.erb
- lib/modules/sorters/agencies.rb
- lib/modules/sorters/reports.rb
- lib/modules/sorters/users.rb
Card for reference: https://trello.com/c/BTYYM7eN/122-ability-to-sort-lists-of-users-and-agencies
> Sort users & agencies

- app/models/ability.rb
> Fixed providers being able to see report summary, locked to their agency

- app/helpers/report_helper.rb
- app/jobs/csv_export_job.rb
- app/views/admin/users/_form.html.erb
- app/views/admin/users/index.html.erb
- app/views/agencies/_form.html.erb
- app/views/agencies/index.html.erb
- app/views/reports/_table.html.erb
- config/secrets.yml
- lib/modules/csv_builder.rb
Make CSV Exports great again. 🙉👑
- Moved awfulness to smaller methods to build components of the csv row
- Added body parts export (each genus is a new row)
- Fixed ENV vars
- Fixed mailer
- Added body parts display into reports table
> Add body parts to csv export

- app/assets/javascripts/components/page_controls.cjsx
- app/assets/javascripts/components/question.cjsx
- app/assets/javascripts/components/save_button.cjsx
- app/assets/javascripts/components/submit_button.cjsx
- app/assets/javascripts/components/tab_controls.cjsx
- app/assets/stylesheets/components/button.scss
- app/assets/stylesheets/components/page-controls.scss
- app/assets/stylesheets/components/table.scss
- app/models/expertise.rb
- app/models/report.rb
- app/views/admin/users/form/_expertise.html.erb
- app/views/reports/_ape_summary.html.erb
- db/migrate/20160912094928_add_kind_to_expertises.rb
- db/migrate/20160912103105_rename_taxonomy_expertises.rb
- db/schema.rb
- db/seeds.rb
Card for reference: https://trello.com/c/56y6Rb9H/128-minor-fixes
> Minor final fixes

- app/assets/stylesheets/components/alert.scss
- app/assets/stylesheets/components/table.scss
- app/controllers/bulk_uploads_controller.rb
- app/models/bulk_upload.rb
- app/models/report.rb
- app/views/bulk_uploads/_errors_table.html.erb
- app/views/bulk_uploads/edit.html.erb
- app/views/bulk_uploads/index.html.erb
- app/views/bulk_uploads/show.html.erb
- app/views/layouts/_header.html.erb
- config/locales/en.yml
- config/routes.rb
- db/migrate/20160908113332_create_bulk_uploads.rb
- db/migrate/20160908115118_add_bulk_upload_id_to_reports.rb
- db/migrate/20160908120309_turn_errors_into_happy_accidents.rb
- db/migrate/20160908120554_add_timestamps_to_bulk_uploads.rb
- db/schema.rb
- lib/modules/csv_converter.rb
- lib/modules/csv_importer.rb
Card for reference: https://trello.com/c/i2lKTFT2/126-implement-csv-import
> Csv import

- app/assets/javascripts/components/questions/form.cjsx
- app/assets/javascripts/stores/questionnaire_store.cjsx
- config/questionnaire/pages.json.erb
- config/questionnaire/pages/incident.json.erb
- config/questionnaire/pages/live.json.erb
- lib/modules/csv_builder.rb
- lib/modules/csv_converter.rb
Cards:
- https://trello.com/c/tjPGili9/147-add-was-ape-for-sale-optional-question
- https://trello.com/c/KyPF2NO4/148-add-date-question-for-collaboration-yes
- https://trello.com/c/NTsXl9eF/156-bug-unable-to-progress-to-next-step-even-when-other-agency-contact-details-are-filled-out
> Add new questions

- app/views/layouts/_footer.html.erb
- package-lock.json
Update logo and use dynamic year in footer.
> use dynamic date in footer
